"use client";

import { FormEvent, useMemo, useState } from "react";

type Priority = "Urgent" | "High" | "Normal" | "Low";
type Status = "New" | "Triaged" | "Investigating" | "Pending customer" | "Escalated" | "Security review" | "Resolved";
type Ticket = {
  id: string; subject: string; customer: string; email: string; category: string;
  priority: Priority; status: Status; security: boolean; age: string; channel: string;
  assigned: string; issue: string; ai: string; resolution: string; tags: string[];
};

const initialTickets: Ticket[] = [
  {id:"NV-1042",subject:"MFA codes are going to my old phone",customer:"Maya Chen",email:"maya@lumenworks.test",category:"Identity & Access",priority:"High",status:"Escalated",security:true,age:"18m",channel:"Email",assigned:"Identity Operations",issue:"I changed phones yesterday and can no longer access my account because the verification code is sent to my old device.",ai:"Confirm the requester through the approved recovery workflow. Check for backup codes or another enrolled factor. Do not disable MFA. Escalate to Identity Operations if recovery methods are unavailable.",resolution:"Identity verification checklist sent. Identity Operations will reset the enrolled factor only after verification is complete.",tags:["mfa","account-recovery"]},
  {id:"NV-1041",subject:"Salesforce sync returns 401",customer:"Northstar Labs",email:"ops@northstar.test",category:"Integration",priority:"High",status:"Investigating",security:false,age:"31m",channel:"Web",assigned:"Tier 2 Support",issue:"Our Salesforce integration stopped overnight. Every sync attempt returns a 401 even after reconnecting the app.",ai:"Confirm token expiry and integration-user permissions, then reconnect with a fresh OAuth grant. Capture the request ID and escalate if the new token also returns 401.",resolution:"Investigation in progress. OAuth token metadata and a failed request ID have been attached for Tier 2 review.",tags:["salesforce","oauth"]},
  {id:"NV-1040",subject:"Suspicious login from an unknown country",customer:"Elena Rossi",email:"elena@vertexline.test",category:"Security Incident",priority:"Urgent",status:"Security review",security:true,age:"39m",channel:"Chat",assigned:"Security On-call",issue:"I received an alert for a successful login from a country I have never visited. I am still able to access the account.",ai:"Do not ask for passwords or authentication codes. Instruct the user to change their password through the official flow, revoke active sessions, preserve sign-in evidence, and notify Security On-call.",resolution:"Sessions revoked by the customer, password reset completed, and sign-in event preserved for security investigation.",tags:["suspicious-login","incident"]},
  {id:"NV-1039",subject:"Unexpected admin permission",customer:"Brightpath Health",email:"it@brightpath.test",category:"Identity & Access",priority:"Urgent",status:"Security review",security:true,age:"47m",channel:"Web",assigned:"Security On-call",issue:"A standard support user appears to have gained workspace-admin access without an approved change request.",ai:"Treat as a potential privilege-escalation incident. Preserve audit logs, avoid changing evidence, notify the security on-call, and follow the incident-response runbook.",resolution:"Audit evidence preserved. Account access contained by an authorized administrator and escalated under incident IR-07.",tags:["rbac","privilege"]},
  {id:"NV-1038",subject:"Account locked after repeated sign-in attempts",customer:"David Okafor",email:"david@freshgrid.test",category:"Identity & Access",priority:"Normal",status:"Pending customer",security:false,age:"55m",channel:"Email",assigned:"Tier 1 Support",issue:"My account was locked after I mistyped my password several times. The self-service reset email has not arrived.",ai:"Verify the email domain, check mail delivery and spam filtering, resend one reset message, and confirm the lockout window. Never request the existing password.",resolution:"Reset email resent after confirming the address. Waiting for the customer to confirm receipt.",tags:["lockout","password-reset"]},
  {id:"NV-1037",subject:"Slack alerts stopped after channel rename",customer:"Helio Finance",email:"admin@helio.test",category:"Integration",priority:"Normal",status:"Triaged",security:false,age:"1h",channel:"Web",assigned:"Integrations Queue",issue:"Ticket alerts stopped appearing in Slack immediately after we renamed the destination channel.",ai:"Confirm the app is still installed, verify channel membership, reselect the renamed channel in integration settings, and send a test notification.",resolution:"Awaiting agent troubleshooting.",tags:["slack","notifications"]},
  {id:"NV-1036",subject:"How do I export a monthly report?",customer:"Oak & Pine",email:"sam@oakpine.test",category:"How-to",priority:"Low",status:"Resolved",security:false,age:"1h",channel:"Chat",assigned:"Tier 1 Support",issue:"I need a CSV of last month’s conversations grouped by assignee. Where can I find that report?",ai:"Open Analytics → Reports, choose the Conversations dataset, filter to last month, group by assignee, and select Export CSV.",resolution:"Provided the reporting steps and a knowledge-base link. Customer confirmed the CSV export was successful.",tags:["analytics","export"]},
  {id:"NV-1035",subject:"API returns 429 during nightly import",customer:"Cardinal Commerce",email:"devops@cardinal.test",category:"API",priority:"High",status:"Escalated",security:false,age:"2h",channel:"API",assigned:"Developer Support",issue:"Our nightly import began returning HTTP 429 after we increased the batch size from 200 to 1,000 records.",ai:"Confirm the documented rate limit, reduce concurrency, implement exponential backoff with jitter, and capture response headers. Escalate only if traffic remains below the stated limit.",resolution:"Reproduction details and rate-limit headers attached. Escalated to Developer Support to confirm tenant-specific limits.",tags:["api","rate-limit"]},
  {id:"NV-1034",subject:"Webhook retries never succeed",customer:"Pollen Studio",email:"tech@pollen.test",category:"Integration",priority:"High",status:"Investigating",security:false,age:"2h",channel:"Email",assigned:"Tier 2 Support",issue:"Our automation webhook times out, then every retry fails even when our endpoint responds normally.",ai:"Check endpoint TLS validity, response time, accepted status codes, and recent delivery logs. Run a test event and compare its correlation ID with failed attempts.",resolution:"A test event is scheduled after the customer confirms the endpoint maintenance window.",tags:["webhook","automation"]},
  {id:"NV-1033",subject:"Dashboard is blank after the latest update",customer:"Monarch Retail",email:"lea@monarch.test",category:"Product Bug",priority:"High",status:"Escalated",security:false,age:"3h",channel:"Chat",assigned:"Product Engineering",issue:"The analytics dashboard loads a blank panel for every manager. Clearing cache and trying another browser did not help.",ai:"Check service status, browser console errors, workspace scope, and a known-issues notice. Capture the workspace ID and a HAR file with sensitive values removed before escalation.",resolution:"Reproduced across two test browsers. Bug record BUG-221 created with sanitized diagnostics and customer impact.",tags:["bug","analytics"]},
  {id:"NV-1032",subject:"Large CSV upload freezes at 82%",customer:"Bluehaven Group",email:"data@bluehaven.test",category:"Product Bug",priority:"Normal",status:"Investigating",security:false,age:"3h",channel:"Web",assigned:"Tier 2 Support",issue:"A 48 MB CSV import consistently freezes at 82%. Smaller files complete normally.",ai:"Validate file size and row limits, encoding, headers, and malformed rows. Split the file to isolate the failing segment and collect the import job ID.",resolution:"Customer asked to test a sanitized split file while Tier 2 reviews import job 78421.",tags:["import","csv"]},
  {id:"NV-1031",subject:"Charged twice for the same subscription",customer:"River & Reed",email:"billing@riverreed.test",category:"Billing",priority:"High",status:"Escalated",security:false,age:"4h",channel:"Email",assigned:"Billing Operations",issue:"Our card statement shows two identical annual subscription charges on the same day.",ai:"Confirm invoice IDs and transaction dates without requesting full card details. Check for duplicate invoices or a pending authorization, then escalate refund decisions to Billing Operations.",resolution:"Two invoice IDs documented. Billing Operations is reviewing the duplicate transaction; no refund was promised by support.",tags:["billing","duplicate-charge"]},
  {id:"NV-1030",subject:"Trial cancellation button is unavailable",customer:"Keystone Legal",email:"office@keystone.test",category:"Subscription",priority:"Normal",status:"Pending customer",security:false,age:"5h",channel:"Chat",assigned:"Customer Operations",issue:"We want to cancel before the trial ends, but the billing page does not show a cancellation option.",ai:"Confirm the requester is a billing admin, identify whether the trial was created through a partner, and provide the correct cancellation path. Do not make retention promises.",resolution:"Waiting for the requester to confirm billing-admin access.",tags:["subscription","cancellation"]},
  {id:"NV-1029",subject:"SSO domain verification remains pending",customer:"Orbit Education",email:"iam@orbit.test",category:"Identity & Access",priority:"High",status:"Investigating",security:true,age:"6h",channel:"Web",assigned:"Identity Operations",issue:"We added the TXT record yesterday, but the SSO setup page still shows our domain as unverified.",ai:"Verify the TXT value and DNS propagation using public lookup tools. Do not ask for DNS credentials. Capture the domain and lookup result, then escalate if the correct record is globally visible.",resolution:"Correct TXT value observed from two resolvers. Escalated to Identity Operations for verification-service review.",tags:["sso","dns"]},
  {id:"NV-1028",subject:"Email notifications arrive 40 minutes late",customer:"Cedar Logistics",email:"helpdesk@cedar.test",category:"Performance",priority:"Normal",status:"Triaged",security:false,age:"8h",channel:"Email",assigned:"Tier 1 Support",issue:"Assignment emails have been arriving around 40 minutes after tickets are created since this morning.",ai:"Check service status, mail provider delays, notification rules, and recent delivery timestamps. Compare in-app event time with email-provider acceptance time.",resolution:"Awaiting initial diagnostics.",tags:["email","latency"]},
  {id:"NV-1027",subject:"Invite link says it has already expired",customer:"Atlas Works",email:"people@atlas.test",category:"How-to",priority:"Low",status:"Resolved",security:false,age:"11h",channel:"Chat",assigned:"Tier 1 Support",issue:"A new teammate receives an expired-link message immediately after I send the invitation.",ai:"Confirm the invite was sent to the correct address, revoke old pending invitations, send one fresh invitation, and have the recipient open only the newest message.",resolution:"Old invitations revoked and a new link issued. The teammate joined successfully.",tags:["invite","onboarding"]},
  {id:"NV-1026",subject:"Workspace deleted by mistake",customer:"Mosaic Travel",email:"owner@mosaic.test",category:"Account & Data",priority:"Urgent",status:"Escalated",security:true,age:"14h",channel:"Phone",assigned:"Account Recovery",issue:"A workspace owner deleted the production workspace and is asking support to restore all customer data immediately.",ai:"Verify owner identity and account scope. Do not promise recovery. Preserve deletion timestamps, check the documented retention window, and escalate to Account Recovery and Privacy teams.",resolution:"Owner-verification process started. Recovery feasibility is under review; no restoration guarantee was given.",tags:["data-recovery","ownership"]},
  {id:"NV-1025",subject:"Request for a complete customer-data export",customer:"Juniper Apps",email:"privacy@juniper.test",category:"Data & Privacy",priority:"High",status:"Security review",security:true,age:"1d",channel:"Email",assigned:"Privacy Operations",issue:"A person claiming to be the company owner wants an immediate export of every user profile and conversation in the workspace.",ai:"Treat as a sensitive data request. Verify authority and identity through the privacy workflow. Do not attach or disclose data in the ticket. Escalate to Privacy Operations.",resolution:"Request logged as PRV-118. No data disclosed; identity and authority verification are pending.",tags:["privacy","data-export"]},
];

const categories = ["All", ...Array.from(new Set(initialTickets.map((t) => t.category)))];

function stageFor(status: Status) {
  if (status === "Resolved") return 5;
  if (status === "Escalated" || status === "Security review") return 4;
  if (status === "Investigating" || status === "Pending customer") return 3;
  if (status === "Triaged") return 2;
  return 1;
}

function triage(subject: string, issue: string) {
  const text = `${subject} ${issue}`.toLowerCase();
  const security = /(mfa|suspicious|unauthori|admin|permission|breach|stolen|privacy|data export)/.test(text);
  const category = /(mfa|login|password|permission|access|sso)/.test(text) ? "Identity & Access" : /(api|429|endpoint)/.test(text) ? "API" : /(sync|integration|webhook|slack|salesforce)/.test(text) ? "Integration" : /(charge|invoice|payment|subscription|cancel)/.test(text) ? "Billing" : /(bug|broken|blank|freeze|error)/.test(text) ? "Product Bug" : "How-to";
  const priority: Priority = /(suspicious|breach|unauthori|deleted|admin)/.test(text) ? "Urgent" : security || /(broken|error|cannot|can't|failed)/.test(text) ? "High" : "Normal";
  const ai = security ? "Use the approved identity-verification or incident workflow. Do not disable security controls, request credentials, or disclose protected data. Preserve evidence and escalate to the appropriate security team." : "Confirm scope and impact, reproduce the issue with safe test data, check service status and documentation, capture relevant IDs and timestamps, then escalate with complete diagnostic context if unresolved.";
  return { security, category, priority, ai };
}

export default function Home() {
  const [tickets, setTickets] = useState(initialTickets);
  const [selectedId, setSelectedId] = useState(initialTickets[0].id);
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("All");
  const [scope, setScope] = useState("Open");
  const [showSubmit, setShowSubmit] = useState(false);
  const [resolutionNote, setResolutionNote] = useState(initialTickets[0].resolution);
  const selected = tickets.find((t) => t.id === selectedId) ?? tickets[0];
  const visibleTickets = useMemo(() => tickets.filter((t) => {
    const matchesQuery = `${t.id} ${t.subject} ${t.customer} ${t.category}`.toLowerCase().includes(query.toLowerCase());
    const matchesCategory = category === "All" || t.category === category;
    const matchesScope = scope === "All" || (scope === "Open" && t.status !== "Resolved") || (scope === "Security" && t.security) || (scope === "Resolved" && t.status === "Resolved");
    return matchesQuery && matchesCategory && matchesScope;
  }), [tickets, query, category, scope]);
  const securityCount = tickets.filter((t) => t.security && t.status !== "Resolved").length;
  const escalatedCount = tickets.filter((t) => ["Escalated","Security review"].includes(t.status)).length;
  const updateSelected = (patch: Partial<Ticket>) => setTickets((items) => items.map((t) => t.id === selected.id ? {...t, ...patch} : t));
  const selectTicket = (id: string) => { const t=tickets.find((item)=>item.id===id); setSelectedId(id); if(t) setResolutionNote(t.resolution); };
  const submitTicket = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form=new FormData(event.currentTarget); const subject=String(form.get("subject")||""); const issue=String(form.get("issue")||""); const customer=String(form.get("customer")||"Demo Customer"); const result=triage(subject,issue); const id=`NV-${1043+tickets.length-initialTickets.length}`;
    const ticket:Ticket={id,subject,customer,email:"customer@demo.test",category:result.category,priority:result.priority,status:"Triaged",security:result.security,age:"Now",channel:"Web",assigned:result.security?"Security Triage":"Tier 1 Support",issue,ai:result.ai,resolution:"Ticket created and automatically triaged. Agent review required.",tags:["simulation","new"]};
    setTickets((items)=>[ticket,...items]); setSelectedId(id); setResolutionNote(ticket.resolution); setShowSubmit(false);
  };
  const exportCsv = () => {
    const rows=[["Ticket","Subject","Customer","Category","Priority","Status","Security-sensitive","Assigned","Resolution"],...tickets.map((t)=>[t.id,t.subject,t.customer,t.category,t.priority,t.status,t.security?"Yes":"No",t.assigned,t.resolution])];
    const csv=rows.map((row)=>row.map((value)=>`"${String(value).replaceAll('"','""')}"`).join(",")).join("\n"); const url=URL.createObjectURL(new Blob([csv],{type:"text/csv"})); const a=document.createElement("a"); a.href=url; a.download="novahelp-ticket-dataset.csv"; a.click(); URL.revokeObjectURL(url);
  };
  const stage=stageFor(selected.status);
  const workflow=["Created","Triaged","Diagnosed",selected.status==="Resolved"?"Resolved":"Escalated","Documented"];
  return <main className="app-shell">
    <header className="topbar"><div className="brand-mark">N</div><div><p className="eyebrow">NOVAHELP CLOUD · PORTFOLIO SIMULATION</p><h1>Support Operations Console</h1><small className="builder">Built by Kosisochukwu Clement Uchebo · Technical Support · SaaS Operations · Identity & Access · AI-Assisted Support</small></div><div className="top-actions"><span className="live-dot"/> Simulation live<button className="export-button" onClick={exportCsv}>Export dataset</button><button className="new-ticket" onClick={()=>setShowSubmit(true)}>+ New ticket</button><div className="avatar">CU</div></div></header>
    <section className="metrics" aria-label="Queue summary"><article><span>Total scenarios</span><strong>{tickets.length}</strong><small>Across 9 categories</small></article><article><span>Security flagged</span><strong>{securityCount}</strong><small>Protected workflow</small></article><article><span>Escalated</span><strong>{escalatedCount}</strong><small>Specialist review</small></article><article><span>Scenario SLA compliance</span><strong>96%</strong><small>Based on simulation dataset · Target 90%</small></article></section>
    <nav className="scope-tabs" aria-label="Ticket scopes">{["Open","Security","Resolved","All"].map((item)=><button className={scope===item?"active":""} key={item} onClick={()=>setScope(item)}>{item}</button>)}<span>{visibleTickets.length} tickets shown</span></nav>
    <section className="workspace">
      <aside className="queue-panel"><div className="panel-heading"><div><p className="eyebrow">TRIAGE QUEUE</p><h2>Active tickets</h2></div></div><div className="queue-tools"><input aria-label="Search tickets" placeholder="Search ticket or customer" value={query} onChange={(e)=>setQuery(e.target.value)}/><select aria-label="Filter by category" value={category} onChange={(e)=>setCategory(e.target.value)}>{categories.map((item)=><option key={item}>{item}</option>)}</select></div><div className="ticket-list">{visibleTickets.map((ticket)=><button className={`ticket-row ${ticket.id===selected.id?"selected":""}`} key={ticket.id} onClick={()=>selectTicket(ticket.id)}><div className="ticket-topline"><span>{ticket.id} · {ticket.category}</span><time>{ticket.age}</time></div><strong>{ticket.subject}</strong><span className="customer">{ticket.customer}</span><div className="ticket-tags"><span className={`priority ${ticket.priority.toLowerCase()}`}>{ticket.priority}</span><span className="mini-status">{ticket.status}</span>{ticket.security&&<span className="security-tag">Security</span>}</div></button>)}{visibleTickets.length===0&&<p className="empty-state">No tickets match these filters.</p>}</div></aside>
      <article className="ticket-panel"><div className="ticket-header"><div><p className="eyebrow">{selected.id} · {selected.category} · {selected.channel}</p><h2>{selected.subject}</h2></div><span className={`status-pill ${selected.security?"risk":""}`}>{selected.status}</span></div><div className="customer-card"><div className="customer-avatar">{selected.customer.slice(0,2).toUpperCase()}</div><div><strong>{selected.customer}</strong><span>{selected.email}</span></div><div className="assignment"><span>Assigned to</span><strong>{selected.assigned}</strong></div></div><div className="message-label">Customer issue</div><div className="message-card"><p>{selected.issue}</p></div><div className="workflow-strip" aria-label="Ticket workflow">{workflow.map((step,index)=><div className={index<stage?"workflow-step done":"workflow-step"} key={step}><span>{index<stage?"✓":index+1}</span><small>{step}</small></div>)}</div><div className="activity"><div className="section-line"><p className="eyebrow">CASE ACTIVITY</p><span>{selected.tags.join(" · ")}</span></div><div><span className="activity-dot"/><p><strong>Ticket captured and categorized</strong><small>{selected.category} · {selected.priority} priority · routing rules applied.</small></p><time>{selected.age}</time></div><div><span className={`activity-dot ${selected.security?"amber":""}`}/><p><strong>{selected.security?"Security-sensitive handling enabled":"AI troubleshooting generated"}</strong><small>{selected.security?"Protected actions require verification and specialist review.":"Agent must validate the suggestion before taking action."}</small></p><time>Automated</time></div><div><span className="activity-dot blue"/><p><strong>Current owner: {selected.assigned}</strong><small>{selected.resolution}</small></p><time>Latest</time></div></div><div className="resolution-box"><div><p className="eyebrow">RESOLUTION DOCUMENTATION</p><small>Record the outcome, evidence, and next step without exposing secrets.</small></div><textarea aria-label="Resolution note" value={resolutionNote} onChange={(e)=>setResolutionNote(e.target.value)}/><button onClick={()=>{updateSelected({resolution:resolutionNote,status:"Resolved",assigned:"Tier 1 Support"});}}>Save & resolve</button></div></article>
      <aside className="ai-panel"><div className="ai-heading"><span>✦</span><div><p className="eyebrow">AI COPILOT</p><h2>Suggested plan</h2></div></div>{selected.security&&<div className="security-banner"><strong>Security-sensitive request</strong><span>Do not disable controls, request credentials, or disclose account data. Verify identity and preserve evidence.</span></div>}<div className="classification"><div><span>Category</span><strong>{selected.category}</strong></div><div><span>Priority</span><strong>{selected.priority}</strong></div><div><span>Route</span><strong>{selected.assigned}</strong></div></div><p className="suggestion">{selected.ai}</p><div className="confidence"><span><b>Simulated suggestion confidence</b><small>Demo score based on scenario risk and routing</small></span><strong>{selected.security?"92%":"88%"}</strong></div><div className="action-stack"><button className="primary-action" onClick={()=>updateSelected({status:"Investigating",assigned:"Tier 1 Support",resolution:"AI troubleshooting plan accepted. Agent validation and diagnostics are in progress."})}>Use troubleshooting plan</button><button className="secondary-action" onClick={()=>updateSelected({status:selected.security?"Security review":"Escalated",assigned:selected.security?"Security On-call":"Tier 2 Support",resolution:`Escalated with category, priority, customer impact, troubleshooting history, and diagnostic evidence.`})}>Escalate with context</button></div><div className="guardrails"><p className="eyebrow">AGENT GUARDRAILS</p><ul><li>Verify AI output before acting</li><li>Never request passwords or MFA codes</li><li>Sanitize logs and attachments</li><li>Document every decision</li></ul></div><p className="ai-note">AI proposes. The support professional verifies and decides.</p></aside>
    </section>
    <section className="evidence"><div><p className="eyebrow">PORTFOLIO EVIDENCE</p><h2>What this simulation demonstrates</h2></div>{["Ticket triage","Troubleshooting","Identity & access","AI-assisted support","Security handling","Escalation","Resolution notes","Jira / Zendesk mapping"].map((item)=><span key={item}>{item}</span>)}</section>
    <footer><span>Designed and built by Kosisochukwu Clement Uchebo · Fictional data only</span><span>Workflow: Created → Triaged → Diagnosed → Resolved or Escalated → Documented</span></footer>
    {showSubmit&&<div className="modal-backdrop" role="presentation"><form className="ticket-modal" role="dialog" aria-modal="true" aria-labelledby="new-ticket-title" onSubmit={submitTicket}><div className="modal-head"><div><p className="eyebrow">CUSTOMER PORTAL</p><h2 id="new-ticket-title">Submit a technical problem</h2></div><button type="button" aria-label="Close" onClick={()=>setShowSubmit(false)}>×</button></div><label>Your name<input name="customer" required placeholder="Demo Customer"/></label><label>Subject<input name="subject" required placeholder="Example: I cannot receive my MFA code"/></label><label>Describe the problem<textarea name="issue" required placeholder="What happened, what did you expect, and what have you tried?"/></label><div className="triage-note"><span>✦</span><p><strong>Automatic triage enabled</strong><small>The simulation assigns category, priority, security handling, and an AI troubleshooting plan.</small></p></div><button className="submit-ticket" type="submit">Create & triage ticket</button></form></div>}
  </main>;
}
